name: 4.3.1-alpine-vaapi-amd64

on: [ workflow_dispatch ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64 \
            --output "type=image,push=false" \
            --tag collelog/ffmpeg:4.3.1-alpine-vaapi-amd64 \
            --file ./4.3.1-alpine-vaapi-amd64.Dockerfile ./
      -
        name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --tag collelog/ffmpeg:4.3.1-alpine-vaapi-amd64 \
            --file ./4.3.1-alpine-vaapi-amd64.Dockerfile ./
      -
        name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery collelog/ffmpeg:4.3.1-alpine-vaapi-amd64
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
